### ISSUE TITLE
Playback Error 400 when trying to cast a stream to YouTube Cast Receiver 

### ISSUE THREAD

**Issue by arlo-infinity** [patrickkfkan/volumio-ytcr#13]
Greetings,

I'm getting "YouTube Cast Receiver could not start playback of blaHBlah: Request to ht<span>tps://</span>www.youtube.com/youtubei/vtrue/next?key=SomethingSomethingSomething&prettyPrint=false&alt=json failed with status 400" every time I try to stream now.   I'm 99% sure that this was working with v3.611 of Volumio and v1.05 of YouTube Cast Receiver as recently as a few weeks ago but I didn't try to cast again until yesterday.   I updated to v3.616 and I thought maybe that broke something, but when used my backup to return to v3.611 it threw the same error there.   I then tried a clean install of Volumio v3.616 onto an empty SD card and again received the same error.

I've read that this 400 error is usually a problem on the client side but I'm stumped because nothing has changed in my network setup in the past weeks and it's not something silly like having a VPN enabled.  I have tried "Clear persisted data" and changing the port from 8098, connecting via TV code, etc.. but no luck.  This happens with both a Pixel 7 and and iPhone 14 Pro, both of which are able to cast YouTube/YouTube Music to other devices on the same network without issue.  Both your YouTube Music and YouTube2, Spotify and every other Plugin including miniDLNA work no problem.  I'm stumped.

Do you have any suggestions for other things to check?  Maybe I'm missing something obvious.

I know it's a longshot but is it possible something is amiss with the API key or the servers ?

Thanks in any case.

![Error](https://github.com/patrickkfkan/volumio-ytcr/assets/121835180/dd7b2226-3b38-40d2-9db9-8b77c56d56f1)

**Comment by patrickkfkan** [comment]
Try v1.0.6 in beta channel of plugin store. Reopen this issue if still not resolved.

**Comment by arlo-infinity** [comment]
@patrickkfkan Thanks for the quick turnaround!  It's back to working perfectly.  Thanks again for making such a useful Plugin.
