### ISSUE TITLE
Unable to cast videos - Unexpected token / receiver is not running

### ISSUE THREAD

**Issue by dzalf** [patrickkfkan/volumio-ytcr#15]
Dear Patrick

First of all, thank you for the great effort put into this plugin.

I have tried several times by reinstalling refreshing and even reflashing a clean image of my Volumio on an RPi5 without success. I keep getting this message when trying to cast a video from the YT App:

<img width="241" alt="image" src="https://github.com/user-attachments/assets/3a40be45-b99e-4f02-8220-43ea44e9e3f4">

Using the YoutTube2 HomeScreen App I get the following error after attempting to play the audio from a video:

<img width="1134" alt="image" src="https://github.com/user-attachments/assets/47b0177b-6050-412e-82e1-25dd2a2b9095">

Strangely, in the configuration screen, I see the message described in the title:

![image](https://github.com/user-attachments/assets/01a91911-75c0-4271-b3c4-ed8ecd1cdc2b)

I cannot find a guide on how to set up a token

Please help with this

Thanks

Cheer

:beer:

**Comment by patrickkfkan** [comment]
Did you try the beta version:

https://community.volumio.com/t/plugin-youtube-cast-receiver/46522/295?u=patrickkfkan

在 2024年8月3日週六 下午2:26，Daniel Melendrez ***@***.***> 寫道：

**Comment by dzalf** [comment]
Hey, @patrickkfkan 

Thanks for the prompt answer.

I managed to solve it by creating an API key on my Google Developer Console, as follows:

1. Login to the Google Developer Console
2. Create a new project. I named mine _VolumioYTCR_
3. Create an API Key in the Credentials section
4. Connect to RPi / Volumio via SSH (assuming this is enabled in the dev/ console)
5. Edit the `config.json` file in `/data/plugins/music_service/ytcr/config.json` by adding the newly created API key:

``` JSON
{
  "apiKey": "YOUR_API_KEY"
}
```
6.  Restart the RPi (I tried by only restarting volumio using `sudo systemctl restart volumio` however it didn't work)

After restarting, now I can see the cast plugin is running and I even get the option to pair using a code:

<img width="815" alt="image" src="https://github.com/user-attachments/assets/cf0a7e42-d128-4086-b829-ca698b4a6533">


I did not need to pair my device. I simply cast the video I wanted and it started playing.

**Comment by patrickkfkan** [comment]
I have no idea what's happening:

1. The YT family of plugins no longer require API keys
2. The `/data/plugins/music_service/youtube_cast/` directory is not created by any of the plugins and therefore does not exist
3. You are mixing screenshots of "YouTube Cast Receiver" plugin and "YouTube2" plugin. They are completely separate plugins.

So I have no clue as to what you are doing here.

**Comment by dzalf** [comment]
Sorry for the confusion.

I don't know how I ended up solving the issue, then.

Please feel free ask me to delete this issue so that we don't confuse people

😢 💫

**Comment by dzalf** [comment]
Well, to be fair, I thought that both plugins worked together in some way

> I have no idea what's happening:
> 
> 1. The YT family of plugins no longer require API keys
> 2. The `/data/plugins/music_service/youtube_cast/` directory is not created by any of the plugins and therefore does not exist
> 3. You are mixing screenshots of "YouTube Cast Receiver" plugin and "YouTube2" plugin. They are completely separate plugins.
> 
> So I have no clue as to what you are doing here.

I have edited my post. I made a mistake with the location of the `json` file.

The plugin certainly worked after adding the API key I generated 😕

**Comment by patrickkfkan** [comment]
As I said, the plugins do not require an API key to function. If a key were required, you would be asked for it in the plugin settings. Things should still work after removing the `apiKey` entry from `config.json`. 

Not restarting Volumio after updating / reinstalling a plugin was most likely the reason.
