### ISSUE TITLE
Issue "Could not start playback"

### ISSUE THREAD

**Issue by PierreM18** [patrickkfkan/volumio-ytcr#17]
Hey Patrick,

First of all thanks for your jobs, the plugins are amazing with a Volumio and a dac to listen music.

I got volumio (3.799) on a rpi3 and the plugin ytcr installed (1.1.2).
When I start the casting from the youtube apps, i got the following error on volumio:
"Could not start playback of ZHc...: Unexpected token (1:47)"

I try to reinstall all of it but it still remains.

Do you got a solution?

Thanks from France,

Pierre

**Comment by Sly1024** [comment]
Same issue here.

I see here on GitHub that the latest version is 2.0.1 but the most recent beta version I can see in volumio is 1.2.0 - I turned on test mode.

How can I install the latest?
I can ssh to my raspberry pi, if that helps.

**Comment by PierreM18** [comment]
I uninstall the 1.1.2, turn on the test mode and then launch the install of the last version.
After reboot it seems work great.
=> Issue solved
Best regard,
