### ISSUE TITLE
[Feature Request] Playlist/Favourites functionality

### ISSUE THREAD

**Issue by maxdd** [patrickkfkan/volumio-ytcr#4]
Hi Patrick,
i was wondering if you are planning, assuming it is even possible (maybe via URL saving), to have the "Add to Playlist" and the "Favourites" functionalities.

**Comment by patrickkfkan** [comment]
If you are talking about adding to playlist / favourite in Volumio player dashboard, here's a remark I made some time ago:

https://community.volumio.org/t/add-to-favourites-playlist-in-player-dashboard/43569

The playlist / favourite implementation in Volumio is not friendly towards 3rd party plugins at all.
