### ISSUE TITLE
unit not found

### ISSUE THREAD

**Issue by yakir12** [patrickkfkan/volumio-ytcr#5]
The mobile phone never finds the RPI after pressing the cast button from the youtube app (it successfully find the TV for instance). Is there anything at all I can do to troubleshot this (I've followed the clear and minimal instructions)?

**Comment by patrickkfkan** [comment]
Try restarting your Volumio and also your phone. If that still doesn't work, go to the plugin settings and enable "Verbose Logging", then do a fresh reboot and go to `http://<volumio_address>/dev` to submit a Log. Copy and paste the link to the log here.

**Comment by yakir12** [comment]
I couldn't find any plugin setting to turn the logging to verbose. But here's the generated link to the report:
http://logs.volumio.org/volumiobuster/pFLuTMK.html

**Comment by patrickkfkan** [comment]
From the logs I cannot see the YouTube Cast Receiver plugin installed. How did you install it?

**Comment by yakir12** [comment]
Facepalm. I followed the following:
> Volumio 3
Plugin submitted to Volumio 3 plugin store. If you do not see it there, enable “Plugins Test Mode” in http://<volumio_address>/dev. If you still do not see it, that means the plugin has not yet been accepted and you are advised to wait.

and saw "a youtube plugin" and installed it. It's the youtube2 plugin... 
![Screenshot from 2021-11-20 13-19-51](https://user-images.githubusercontent.com/3281957/142726187-4f017a5a-f205-49a3-8e22-3f5be78b91cb.png)

Apologies for the noise.

But does that mean that I can't get `ytcr`?

**Comment by patrickkfkan** [comment]
The youtube2 plugin does not include ytcr.
I have already submitted the ytcr plugin to Volumio 3. You would have to wait for them to accept it.

**Comment by yakir12** [comment]
(was there a way for me to get it installed nevertheless? I can burn a new volumio version just to try ytcr)

**Comment by patrickkfkan** [comment]
Do you know how to ssh into your Volumio?

**Comment by yakir12** [comment]
yes sir :)

**Comment by patrickkfkan** [comment]
After ssh:
```
$ git clone https://github.com/patrickkfkan/volumio-ytcr
$ cd volumio-ytcr
$ volumio plugin install
```

**Comment by yakir12** [comment]
Totally worked. Thanks a lot. Also, wow `volumio plugin install` is so streamlined! (I need to go look for more plugins!) Thank you!
