### ISSUE TITLE
[Feature Request] Youtube music support

### ISSUE THREAD

**Issue by Freeburn113** [patrickkfkan/volumio-ytcr#6]
Hi,

I was wondering if it would be hard to implement youtube music support to your plugin. I mainly use this as my music player so it would be awesome if I could stream this with the plugin too.

**Comment by patrickkfkan** [comment]
YouTube Music uses a later version of the Cast protocol and authenticates the device being cast to. It is impossible to emulate a cast receiver device that can pass this authentication stage.
